djangolearn/blog/urls.py
"""Defines URL patterns for blog."""
from django.contrib import admin
from django.urls import path, include

from . import views

app_name= 'blog'

urlpatterns = [
    # API urls
    #path('', include('myapi.urls')),

    # Home page.
    path('', views.index, name='index'),

    # Page that showing all topics.
    path('topics/', views.topics, name='topics'),

    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new Topic.
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding a new entry.
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),

    # Page for editing entries
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry')
]   

djangolearn/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from myapi.views import *

# Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'groups', GroupViewSet)


urlpatterns = [
    # Admin URLs
    path('admin/', admin.site.urls),

    # API URLs
    #path('', include('myapi.urls')),
    #path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Models URLs
    path('', include('blog.urls')),
    path('', include('users.urls')),
]

djangolearn/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include


from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    # Registration page
    path('refister/', views.register, name='register')

]

djangolearn/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
        def __str__(self):
            """Return a string representation of the model."""
            return f"{self.text[:50]}..."
            

djangolearn/users/models.py
from django.db import models

# Create your models here.

djangolearn/blog/forms.py
from django import forms

from .models import Entry, Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
                

djangolearn/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404


from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Blog."""
    return render(request, 'blog/index.html')


@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'blog/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show one selected topic."""
    topic = Topic.objects.get(id=topic_id)
    # Except the topic belongs to the current user.
    if topic.owner != request.user:
        return Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'blog/topic.html', context) 


@login_required
def new_topic(request):
    """Add new topic."""
    if request.method != 'POST':
        # No data submitted. Create blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:topics')

    # Display blank or invalid form.
    context = {'form': form}
    return render(request, 'blog/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
 
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('blog:topic', topic_id=topic_id)
            
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'blog/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'blog/edit_entry.html', context)

djangolearn/myapi/views.py
from rest_framework import viewsets, permissions
from . import serializers
from django.contrib.auth.models import User, Group


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = serializers.UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = serializers.GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

djangolearn/users/views.py
from urllib import request
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blog:index')

    context = {'form': form}

    return render(request, 'registration/register.html', context)

djangolearn/blog/templates/blog/edit_entry.html
{% extends "blog/main.html" %}
{% block content %}
    <p><a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a></p>
 
    <p>Edit entry:</p>

    <form action="{% url 'blog:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Save changes</button>
    </form>
 
{% endblock content %}

djangolearn/blog/templates/blog/index.html
{% extends "blog/main.html" %}
{% load static %}
{% block content %}
    <p class="body">This is simple body text on main page.</p>
{% endblock content %}

djangolearn/blog/templates/blog/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Encore</title>
  </head>
  <body>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block style %}
    {% endblock style %}
    {% include "blog/navbar.html" %}
    {% block content %}
    {% endblock content %}
  </body>
</html>

djangolearn/blog/templates/blog/navbar.html
{% load static %}
<h1>
    <i class="fas fa-home"> <a href="{% url 'blog:index' %}">Main page</a> </i> -
    <i class="fas fa-hashtag"><a href="{% url "blog:topics" %}">Topics</a> </i> -
    {% if user.is_authenticated %}
        <a href="">Hello, {{user.username.capitalize}}</a>
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</h1>

djangolearn/blog/templates/blog/new_entry.html
{% extends "blog/main.html" %}
{% block content %}
    <p><a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a></p>
 
    <p>Add a new entry:</p>
    <form action="{% url 'blog:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
     <button name='submit'>Add entry</button>
    </form>
 
{% endblock content %}

djangolearn/blog/templates/blog/new_topic.html
{% extends "blog/main.html" %}

{% block content %}
 <p>Add a new topic:</p>
 
 <form action="{% url 'blog:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
     <button name="submit">Add topic</button>
 </form>
 
{% endblock content %}

djangolearn/blog/templates/blog/topic.html
{% extends "blog/main.html" %}

{% block content %}

  <p>Topic <b>{{ topic }}</b></p>
  <p>
    <a href="{% url 'blog:new_entry' topic.id %}">Add new entry</a>
  </p>

  <p>Entries:</p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ entry.text|linebreaks }}</p>
      <p>
        <a href="{% url 'blog:edit_entry' entry.id %}">Edit entry</a>
      </p>
    </li>
 {% empty %}
   <li>There are no entries for this topic yet.</li>
 {% endfor %}
 </ul>
{% endblock content %}

djangolearn/blog/templates/blog/topics.html
{% extends "blog/main.html" %}
{% block content %}
    <p>
      <h1>Topics ({{ topics|length }} items)</h1>
      <h2>
        <a href="{% url 'blog:new_topic' %}">Add</a>
      </h2>
    </p>
    {% for topic in topics %}
      <h2>{{forloop.counter}}. {{ topic }} (
      <a href={% url 'blog:topic' topic.id %}>Read</a>
      <a href="{% url 'blog:new_topic' %}">Edit</a>
      <a href="{% url 'blog:new_topic' %}">Delete</a>
      )
      </h2>
    {% empty %}
      <p>No topics have been added yet.</p>
    {% endfor %}
  {% endblock content %}