blog/urls.py
"""Defines URL patterns for blog."""

from django.urls import path

from . import views

app_name= 'blog'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),

    # Page that showing all topics.
    path('topics/', views.topics, name='topics'),

    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new Topic.
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding a new entry.
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
]

blog/forms.py
from django import forms

from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blog/views.py
from django.shortcuts import render, redirect

from .models import Topic
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Blog."""
    return render(request, 'blog/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'blog/topics.html', context)

def topic(request, topic_id):
    """Show one selected topic."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'blog/topic.html', context) 

def new_topic(request):
    """Add new topic."""
    if request.method != 'POST':
        # No data submitted. Create blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:topics')

    # Display blank or invalid form.
    context = {'form': form}
    return render(request, 'blog/new_topic.html', context)


def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
 
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
            
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>HOME</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<p>
  <a href="{% url 'blog:index' %}">Main page</a> - 
  <a href="{% url 'blog:topics' %}">Topics</a>
</p>
{% block content %}{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
  <p>Learning Log hepls you keep track of your learning! </p>
{% endblock content %}

blog/templates/blog/new_topic.html
{% extends "blog/base.html" %}

{% block content %}
 <p>Add a new topic:</p>
 
 <form action="{% url 'blog:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
     <button name="submit">Add topic</button>
 </form>
 
{% endblock content %}

blog/templates/blog/topic.html
{% extends "blog/base.html" %}

{% block content %}

  <p>Topic {{ topic }}</p>

  <p>Entries:</p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ entry.text|linebreaks }}</p>
    </li>
 {% empty %}
   <li>There are no entries for this topic yet.</li>
 {% endfor %}
 </ul>
{% endblock content %}

blog/templates/blog/topics.html
{% extends "blog/base.html" %}

{% block content %}

  <a href="{% url 'blog:new_topic' %}">Add a new topic</a>

  <p><B>Existing topics</B> ({{ topics|length }} items)</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  
{% endblock content %}